version: '3'  # docker-composeファイルの構文バージョン
services:  # コンポースするサービスたち
    go_server:  # サービスの名前
        image: golang:1.22.2-bullseye  # pullするイメージ
        container_name: kakuninkun_api  # コンテナ名
        volumes:  # ボリュームの保持。
            - ./share:/root/share
        build:  # ビルド設定
            context: .  # ビルドプロセスが実行されるパス。通常はDockerfileが存在するパス。
            dockerfile: ./build/Dockerfile  # Dockerfileのパス。
        tty: true  # コンテナ内で対話的操作を可能
    muysql_server: 
        image: mysql:latest
        container_name: kakuninkun_db
        restart: always
        environment:
            TZ: "Asia/Tokyo"
        env_file: 
            - .env
        ports:
            - "3307:3306"  # ホストマシンのポートとコンテナのポートをマッピング
        volumes:
            - ./mysql-data:/var/lib/mysql